### ISSUE TITLE
migration error

### ISSUE THREAD

**Issue by Sigurgeirstephensen** [hgop/syllabus-2022#45]
migration er ekki að virka fyrir acceptence í dag 8 en ég er ekki búin að breyta neinu nema hlutum sem við áttum að breyta en samt þegar ég skoða þá kemur 
<img width="961" alt="Screenshot 2022-12-01 at 12 05 14" src="https://user-images.githubusercontent.com/70693413/205048468-e5c22cb0-332c-4a5b-bf3a-490555ec905b.png">

og svo er þetta þegar ég geri get pods
<img width="766" alt="Screenshot 2022-12-01 at 12 05 46" src="https://user-images.githubusercontent.com/70693413/205048558-a6766846-62c5-4e06-9828-9037fe130389.png">

**Comment by Sigurgeirstephensen** [comment]
../.pyenv/versions/3.8.15/lib/python3.8/site-packages/requests/adapters.py:565: ConnectionError
=========================== short test summary info ============================
FAILED src/connect4-server/src/tests/acceptance/test_status.py::test_status - requests.exceptions.ConnectionError: HTTPSConnectionPool(host='connect4-server.acceptance.%7b%7bteam_name%7d%7d.hgopteam.com', port=443): Max retries exceeded with url: //status (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0ea65d130>: Failed to establish a new connection: [Errno -2] Name or service not known'))
============================== 1 failed in 0.23s =============================== 

þetta er error sem kemur út af þessu núna í acceptance test 
https://circleci.com/api/v1.1/project/github/Sigurgeirstephensen/Quality-Assurance---course/525/output/103/0?file=true&allocation-id=63889b503c47c33d14e1bb93-0-build%2F45C54939

**Comment by finnure** [comment]
Samkvæmt fyrsta screenshot frá þér ertu að nota testing123 sem database username. Kóðinn sem var gefinn til að búa til acceptance gagnagrunninn gerir ráð fyrir að bæði user og pass sé connect4. Breyttir þú DATABASE_USERNAME í create-acceptance-environment skrefinu fyrir circleci?
Svona ætti þetta að líta út í circleci config.yaml:
```yaml
  create-acceptance-environment:
    docker:
      - image: cimg/base:stable
    environment:
      DATABASE_USERNAME: connect4
      DATABASE_PASSWORD: connect4
      CONNECT4_SERVER_DATABASE_USERNAME: Y29ubmVjdDQ=
      CONNECT4_SERVER_DATABASE_PASSWORD: Y29ubmVjdDQ=
```
Villan sem þú ert að fá í circleci þegar þú keyrir acceptance test er vegna þess að API_URL í acceptance-test job hjá þér er með {{team_name}} í urlinu. Gleymdiru að replace-a því með actual teamname?
