### ISSUE TITLE
Fæ ekki acceptance umhverfið til að keyra

### ISSUE THREAD

**Issue by Hjortur17** [hgop/syllabus-2022#69]
Er að reyna að koma client acceptance umhverfinu upp en fæ bara 404 villu. 

Það sem ég gerði var að nota það sem við vorum búinn að gera með serverinn og endurnýtti það. Tók bara allt út sem tengist gagnagrunninum. Hérna er hvernig job-ið mitt lýttur út núna:

```
create-client-acceptance-environment:
    docker:
      - image: cimg/base:stable
    environment:
      PROJECT_DIRECTORY: ./src/connect4-client
      API_URL: "http://connect4.acceptance.b3g.hgopteam.com"
    steps:
    - checkout
    - kubernetes/install-kubectl
    - kubernetes/install-kubeconfig:
        kubeconfig: KUBECONFIG_DATA
    - run: ./scripts/ci/deploy/create.sh "connect4-client" "${CIRCLE_SHA1}" > connect4-client.yaml
    - run: kubectl apply --namespace acceptance -f connect4-client.yaml
```

Síðan er pipelineið mitt einhvern veginn svona:

```
workflows:
  pipeline:
    jobs:
      - build-and-publish
      - create-client-acceptance-environment
      - client-acceptance-test:
            requires:
              - build-and-publish
              - create-client-acceptance-environment
      - deploy
          requires:
                - build-and-publish
                - client-acceptance-test
```
